from datetime import datetime
from typing import Dict, List, Optional

from .config import Config
from .memory_store import MemoryStore

REFLECTION_QUESTIONS = [
    "What did the system learn from these memories?",
    "What patterns or themes repeat across these memories?",
    "What seems most important, and why?",
    "What should be preserved as long-term core memory?",
    "What tasks or experiments are implied by these memories?",
]


def reflect(config: Optional[Config] = None) -> Dict:
    """Review all episodic and semantic memories and produce a reflection note."""
    if config is None:
        config = Config()

    store = MemoryStore(config)
    episodic = store.list_memories("episodic")
    semantic = store.list_memories("semantic")

    if not episodic and not semantic:
        return {"reflection": None, "message": "No episodic or semantic memories to reflect on."}

    source_ids = [m["id"] for m in episodic + semantic]
    all_tags = list({tag for m in episodic + semantic for tag in m.get("tags", [])})

    content = _generate_reflection(episodic, semantic)
    reflection = store.store_reflection(content=content, source_ids=source_ids, tags=all_tags)

    return {"reflection": reflection, "message": "Reflection created."}


def _generate_reflection(episodic: List[Dict], semantic: List[Dict]) -> str:
    lines = [
        f"## Recursive Reflection — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
        "",
        f"Reviewing {len(episodic)} episodic memories and {len(semantic)} semantic memories.",
        "",
    ]

    # Tag frequency analysis
    tag_counts: Dict[str, int] = {}
    for m in episodic + semantic:
        for tag in m.get("tags", []):
            tag_counts[tag] = tag_counts.get(tag, 0) + 1

    if tag_counts:
        top_tags = sorted(tag_counts.items(), key=lambda x: -x[1])[:5]
        lines.append("### Dominant Themes")
        for tag, count in top_tags:
            lines.append(f"- **{tag}** (appears {count} time(s))")
        lines.append("")

    # High-importance memories
    high = [m for m in episodic + semantic if m.get("importance", 0) >= 0.6]
    if high:
        lines.append("### High-Importance Memories")
        for m in high:
            if m["type"] == "episodic":
                lines.append(f"- [[{m['id']}]] {m.get('summary', '')[:100]}")
            else:
                lines.append(f"- [[{m['id']}]] Concept: {m.get('concept', '')}")
        lines.append("")

    # Reusable concepts
    if semantic:
        lines.append("### Reusable Concepts Identified")
        for m in semantic:
            desc = m.get("description", "")[:80]
            lines.append(f"- **{m.get('concept', 'Unknown')}**: {desc}")
        lines.append("")

    # Reflection questions (for human or LLM review)
    lines.append("### Reflection Questions")
    for q in REFLECTION_QUESTIONS:
        lines.append(f"- {q}")
    lines.append("")

    # Implied tasks
    lines.append("### Implied Tasks")
    task_tags = [t for t in tag_counts if t in ("task", "experiment", "goal", "project")]
    if task_tags:
        for tag in task_tags:
            lines.append(f"- Review memories tagged `{tag}` for actionable follow-up.")
    else:
        lines.append("- No task-specific tags found. Consider reviewing for implied next steps.")
    lines.append("")

    lines.append("### Note")
    lines.append(
        "This reflection was generated by rule-based analysis. "
        "Replace `reflect.py:_generate_reflection` with an LLM call when ready."
    )

    return "\n".join(lines)
